---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(flexdashboard)
library(plotly)
library(tidyverse)
library(viridis)
library(shiny)

NYPD_Shooting_Incident<- read_csv("data/NYPD_Shooting_Incident_Data__Historic__20231120.csv") %>% janitor::clean_names()

NYPD_Shooting_Incident_cleaned = 
  NYPD_Shooting_Incident |>
  separate(occur_date, into = c("month", "day", "year"), sep = "/") |>
  separate(occur_time, into = c("hour", "minute", "second"), sep = ":") |>
  select(-minute, -second, -loc_of_occur_desc, -loc_classfctn_desc, -location_desc)

NYPD_Shooting_Incident_cleaned_2 <- 
  NYPD_Shooting_Incident_cleaned %>% 
  rename(lat = latitude, lon = longitude) %>%
  select(boro, lat, lon,statistical_murder_flag,year,vic_age_group)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_vec <-
  NYPD_Shooting_Incident_cleaned_2 %>% pull(boro) %>% unique()

selectInput(
  inputId = "borough_choice",
  label = h3("Selcet Borough"),
  choices = borough_vec,
  selected = "MANHATTAN",
  multiple = TRUE
)

sliderInput(
  inputId = "year_range",
  label = h3("Selcet a year range"),
  max = 2022, min = 2006,
  value = c(2010,2015)
)

vic_age <- 
  NYPD_Shooting_Incident_cleaned_2 %>% pull(vic_age_group) %>% unique()

selectInput(
  inputId = "victim_age",
  label = h3("Select Age Group"),
  choices = vic_age,
  selected = "<18"
)

statistical_murder_flag <-
  NYPD_Shooting_Incident_cleaned_2 %>% pull(statistical_murder_flag) %>% unique()

radioButtons(
  inputId = "statistical_murder_flag",
  label = h3("Select Murder Status"),
  choices = statistical_murder_flag
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  NYPD_Shooting_Incident_cleaned_2 |> 
  filter(
    boro == input[["borough_choice"]],
    year < input[["year_range"]][2],
    year > input[["year_range"]][1],
    vic_age_group == input[["victim_age"]]
    ) |> 
  plot_ly(x = ~lon,
          y = ~lat, 
          type = "scatter",
          mode = "markers",
          color = ~boro) %>%
    layout(
    geo = list(
      scope = 'usa',
      showland = TRUE,
      landcolor = toRGB("gray90"),
      countrycolor = toRGB("gray80"),
      showlakes = TRUE,
      lakecolor = toRGB("blue"),
      subunitcolor = toRGB("gray80"),
      center = list(lon = -74.0060, lat = 40.7128), # Center on NYC
      projection = list(type = 'albers usa'),
      zoom = 7
    )
  )
})

```
Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  NYPD_Shooting_Incident_cleaned_2 %>% 
    filter(boro == input[["borough_choice"]],
    year < input[["year_range"]][2],
    year > input[["year_range"]][1],
    vic_age_group == input[["victim_age"]]) %>%
    mutate(boro = fct_reorder(boro, year)) %>% 
    plot_ly(y = ~year, color = ~boro, type = "box", colors = "viridis")
})
```

### Chart C

```{r}
renderPlotly({NYPD_Shooting_Incident_cleaned_2 %>%
  filter(boro == input[["borough_choice"]],
    year < input[["year_range"]][2],
    year > input[["year_range"]][1],
    vic_age_group == input[["victim_age"]]) %>%
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")
})
```


### Chart D

```{r}

renderPlotly({NYPD_Shooting_Incident_cleaned_2 %>%
  filter(boro == input[["borough_choice"]],
    year < input[["year_range"]][2],
    year > input[["year_range"]][1],
    vic_age_group == input[["victim_age"]]) %>%
  plot_ly(x = ~lat, y = ~lon, color = ~year, type = "scattergeo", colors = "viridis")
}) 
```

